# Generated by Django 4.0.4 on 2022-05-17 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Enter car number', max_length=10, verbose_name='number')),
                ('vin_number', models.CharField(help_text='17 symbols <a href="https://www.autodna.com/vin-number">VIN number</a>', max_length=17, verbose_name='VIN number')),
                ('client', models.CharField(help_text='Enter client name', max_length=250, verbose_name='client')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(help_text='Enter car brand (for example, Toyota)', max_length=100, verbose_name='car band')),
                ('car_model', models.CharField(help_text='Enter car model (for example, Corolla)', max_length=100, verbose_name='car model')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='order data')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.car')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', help_text='Service name', max_length=100)),
                ('price', models.FloatField(help_text='service price', verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='service quantity', verbose_name='quantity')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.order')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.service')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.model'),
        ),
    ]
