# Generated by Django 4.0.4 on 2022-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='year',
            field=models.IntegerField(help_text='Enter car production year', null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='model',
            name='car_brand',
            field=models.CharField(help_text='Enter car brand (for example, Toyota)', max_length=100, verbose_name='car brand'),
        ),
    ]
